// ---------------------------------------------------------------------------
// Attack definitions
//
// `startup`/`active`/`recovery` (ms) drive BOTH the hitbox timing AND the
// animation phase timing (AnimationController reads the same numbers), so
// the visual windup/strike/recovery always matches when the hit can land.
// ---------------------------------------------------------------------------

export const ATTACKS = {
  lightPunch: {
    id: 'lightPunch',
    poseWindup: 'punchWindup',
    poseStrike: 'punchStrike',
    startup: 150,
    active: 90,
    recovery: 180,
    damage: 6,
    knockback: 190,
    knockbackUp: -60,
    hitstun: 260,
    range: 62,
    reachY: -70, // offset from feet, negative = up (roughly chest height)
    height: 34,
    cooldown: 120,
    requiresGrounded: true,
    cancelableAfter: 0.3,
  },
  heavyPunch: {
    id: 'heavyPunch',
    poseWindup: 'heavyWindup',
    poseStrike: 'heavyStrike',
    startup: 260,
    active: 110,
    recovery: 340,
    damage: 15,
    knockback: 360,
    knockbackUp: -140,
    hitstun: 420,
    range: 70,
    reachY: -72,
    height: 36,
    cooldown: 200,
    requiresGrounded: true,
    cancelableAfter: 0.65,
  },
  kick: {
    id: 'kick',
    poseWindup: 'kickWindup',
    poseStrike: 'kickStrike',
    startup: 190,
    active: 110,
    recovery: 260,
    damage: 10,
    knockback: 280,
    knockbackUp: -100,
    hitstun: 340,
    range: 78,
    reachY: -34,
    height: 32,
    cooldown: 160,
    requiresGrounded: true,
    cancelableAfter: 0.45,
  },
  airAttack: {
    id: 'airAttack',
    poseWindup: 'airWindup',
    poseStrike: 'airStrike',
    startup: 120,
    active: 100,
    recovery: 160,
    damage: 9,
    knockback: 240,
    knockbackUp: -40,
    hitstun: 300,
    range: 68,
    reachY: -30,
    height: 40,
    cooldown: 140,
    requiresAirborne: true,
  },
  dashAttack: {
    id: 'dashAttack',
    poseWindup: 'punchWindup',
    poseStrike: 'heavyStrike',
    startup: 90,
    active: 110,
    recovery: 240,
    damage: 10,
    knockback: 330,
    knockbackUp: -80,
    hitstun: 360,
    range: 76,
    reachY: -60,
    height: 40,
    cooldown: 220,
    requiresGrounded: true,
    dashSpeed: 620,
  },
  special: {
    id: 'special',
    poseWindup: 'specialWindup',
    poseStrike: 'specialStrike',
    startup: 380,
    active: 140,
    recovery: 380,
    damage: 26,
    knockback: 460,
    knockbackUp: -220,
    hitstun: 520,
    range: 100,
    reachY: -66,
    height: 52,
    cooldown: 300,
    requiresGrounded: true,
    energyCost: 100,
  },
};

export function totalAttackDuration(attack) {
  return attack.startup + attack.active + attack.recovery;
}
